import json, os
base = "/gfin/artifacts/investigations/smartstar-uk-007"
def save(name, data):
    with open(os.path.join(base, name), 'w') as f:
        json.dump(data, f, indent=2)

# 1
save("case.json", {"case_id":"CASE-SMARTSTAR-UK-007","title":"Full Digital Investigation / Universal Source & API Discovery","version":"1.0","target":{"name":"SmartStar Technology Ltd","number":"14511663","jurisdiction":"UK"},"investigative_objective":"Reconstruct complete evidence ecosystem","available_authority":"public OSINT only","classification":"UNCLASSIFIED","resource_budget":"sandbox","investigator":"GFIN-CEA (GPT Luna)","timestamp":"2026-08-26T18:20:00Z","source_blind":True,"provider_blind":True,"api_blind":True})

# 2
save("investigation-plan.json", {"operator_provided":["case_id","target_name","company_number","jurisdiction","investigative_objective","available_authority","classification","resource_budget"],"operator_did_not_provide":["known domains","known people","known emails","known phones","known wallets","known APIs","known providers","known related companies","known social accounts"],"discovery_sequence":["Companies House UK (direct web) → company + officers","DNS over HTTPS → domain discovery","RDAP → domain registration data","GitHub API → code repos + email","Apple iTunes API → app ecosystem","Wayback CDX → historical web","Etherscan API → blockchain check","BAILII → court records","OpenSanctions → watchlists","Action Fraud → victim reports","Open Ownership → beneficial ownership","FCA Register → regulatory","VirusTotal → threat intelligence"],"stop_conditions":["all source classes exhausted","authorization boundary reached","information gain low","case objective sufficiently answered"]})

# 3
save("reasonable-lines.json", {"lines":[{"id":"L1","line":"Corporate reconstruction — company filings, officers, PSC, capital","status":"EXHAUSTED","evidence":8},{"id":"L2","line":"People investigation — Rojs Gordons (6 UK companies, 5 international)","status":"EXHAUSTED","evidence":12},{"id":"L3","line":"Digital infrastructure — DNS, RDAP, domains, IP intelligence","status":"EXHAUSTED","evidence":15},{"id":"L4","line":"Code repository intelligence — GitHub API for Protremix","status":"EXHAUSTED","evidence":5},{"id":"L5","line":"App ecosystem — Apple iTunes API + Google Play","status":"EXHAUSTED","evidence":4},{"id":"L6","line":"Historical web — Wayback Machine CDX","status":"EXHAUSTED","evidence":2},{"id":"L7","line":"Court/legal — BAILII, judiciary.uk, tribunal decisions","status":"EXHAUSTED (no results)","evidence":0},{"id":"L8","line":"Sanctions/watchlists — OpenSanctions","status":"AUTH_REQUIRED","evidence":0},{"id":"L9","line":"Victim complaints — Action Fraud, FCA, consumer protection","status":"AUTH_REQUIRED","evidence":0},{"id":"L10","line":"Financial — banking, payments, merchant","status":"AUTH_REQUIRED","evidence":0},{"id":"L11","line":"Crypto — Etherscan (testnet only, no mainnet)","status":"EXHAUSTED (no wallet)","evidence":0},{"id":"L12","line":"Social platforms — LinkedIn, Facebook (OAuth required)","status":"AUTH_REQUIRED","evidence":0},{"id":"L13","line":"Advertising — ad libraries (APIs not implemented)","status":"NOT_IMPLEMENTED","evidence":0},{"id":"L14","line":"GEOINT — mapping/satellite (not implemented)","status":"NOT_IMPLEMENTED","evidence":0},{"id":"L15","line":"Cross-border — Poland, France, Czech, Spain, Estonia","status":"PARTIAL (via CASE-002)","evidence":5}]})

# 4
save("source-discovery.json", {"sources_discovered":[{"source":"Companies House UK","class":"OFFICIAL_REGISTRIES","url":"find-and-update.company-information.service.gov.uk","access":"PUBLIC (web)","api":"AUTH_REQUIRED","result":"SUCCESS"},{"source":"Google DoH","class":"DNS","url":"8.8.8.8/resolve","access":"PUBLIC","api":"PUBLIC","result":"SUCCESS"},{"source":"Cloudflare DoH","class":"DNS","url":"1.1.1.1/dns-query","access":"PUBLIC","api":"PUBLIC","result":"SUCCESS"},{"source":"RDAP (rdap.org)","class":"DOMAIN_REGISTRATION","url":"rdap.org/domain/{domain}","access":"PUBLIC","api":"PUBLIC","result":"SUCCESS"},{"source":"Verisign RDAP","class":"DOMAIN_REGISTRATION","url":"rdap.verisign.com/com/v1/domain/{domain}","access":"PUBLIC","api":"PUBLIC","result":"SUCCESS"},{"source":"Wayback Machine CDX","class":"HISTORICAL_ARCHIVES","url":"web.archive.org/cdx","access":"PUBLIC","api":"PUBLIC","result":"SUCCESS"},{"source":"GitHub API","class":"CODE_REPOSITORIES","url":"api.github.com","access":"PUBLIC (rate limited)","api":"PUBLIC","result":"SUCCESS"},{"source":"Apple iTunes Search API","class":"APP_STORES","url":"itunes.apple.com/search","access":"PUBLIC","api":"PUBLIC","result":"SUCCESS"},{"source":"Apple iTunes Lookup API","class":"APP_STORES","url":"itunes.apple.com/lookup","access":"PUBLIC","api":"PUBLIC","result":"SUCCESS"},{"source":"Etherscan API","class":"BLOCKCHAIN","url":"api.etherscan.io/api","access":"PUBLIC (free tier)","api":"PUBLIC","result":"SUCCESS (no data)"},{"source":"BAILII","class":"COURTS_LEGAL","url":"bailii.org","access":"PUBLIC","api":"PUBLIC (search)","result":"NO_CASES_FOUND"},{"source":"OpenSanctions","class":"SANCTIONS","url":"api.opensanctions.org","access":"AUTH_REQUIRED","api":"AUTH_REQUIRED","result":"AUTH_REQUIRED"},{"source":"Action Fraud UK","class":"VICTIM_COMPLAINTS","url":"actionfraud.police.uk","access":"RESTRICTED","api":"NO_PUBLIC_API","result":"AUTH_REQUIRED"},{"source":"FCA Register","class":"REGULATORY","url":"register.fca.org.uk","access":"RESTRICTED","api":"RESTRICTED","result":"403_FORBIDDEN"},{"source":"Open Ownership Register","class":"BENEFICIAL_OWNERSHIP","url":"register.openownership.org","access":"RESTRICTED","api":"RESTRICTED","result":"403_FORBIDDEN"},{"source":"VirusTotal","class":"THREAT_INTELLIGENCE","url":"virustotal.com/api","access":"AUTH_REQUIRED","api":"AUTH_REQUIRED","result":"401_UNAUTHORIZED"},{"source":"Google Safe Browsing","class":"THREAT_INTELLIGENCE","url":"safebrowsing.googleapis.com","access":"AUTH_REQUIRED","api":"AUTH_REQUIRED","result":"AUTH_REQUIRED"},{"source":"crt.sh","class":"CERTIFICATE_TRANSPARENCY","url":"crt.sh","access":"PUBLIC","api":"PUBLIC","result":"502_UNAVAILABLE"}],"total_sources":18,"sources_successful":9,"auth_required":7,"unavailable":2})

# 5
save("provider-discovery.json", {"providers":[{"name":"Companies House UK","coverage":"UK corporate filings","api":"REST (auth required for API)","auth":"API key (Basic Auth)","connector":"Web access used (API auth required)","result":"SUCCESS"},{"name":"Google DoH","coverage":"Global DNS","api":"HTTPS JSON","auth":"None","connector":"Direct HTTPS","result":"SUCCESS"},{"name":"Cloudflare DoH","coverage":"Global DNS","api":"HTTPS JSON","auth":"None","connector":"Direct HTTPS","result":"SUCCESS"},{"name":"RDAP / IETF","coverage":"Domain registration","api":"REST JSON","auth":"None","connector":"Direct HTTPS","result":"SUCCESS"},{"name":"Verisign","coverage":".com domain registration","api":"REST JSON","auth":"None","connector":"Direct HTTPS","result":"SUCCESS"},{"name":"Internet Archive","coverage":"Historical web","api":"CDX JSON","auth":"None","connector":"Direct HTTPS","result":"SUCCESS"},{"name":"GitHub","coverage":"Code repositories","api":"REST JSON","auth":"None (rate limited)","connector":"Direct HTTPS","result":"SUCCESS"},{"name":"Apple","coverage":"App Store metadata","api":"REST JSON","auth":"None","connector":"Direct HTTPS","result":"SUCCESS"},{"name":"Etherscan","coverage":"Ethereum blockchain","api":"REST JSON","auth":"API key (optional)","connector":"Direct HTTPS","result":"SUCCESS (no data)"},{"name":"BAILII","coverage":"UK/Irish case law","api":"Web search","auth":"None","connector":"Direct HTTPS","result":"NO_CASES"},{"name":"OpenSanctions","coverage":"Global sanctions/watchlists","api":"REST JSON","auth":"API key required","connector":"NOT_IMPLEMENTED","result":"AUTH_REQUIRED"},{"name":"VirusTotal","coverage":"Threat intelligence","api":"REST JSON","auth":"API key required","connector":"NOT_IMPLEMENTED","result":"AUTH_REQUIRED"}],"total_providers":12})

# 6
save("api-discovery.json", {"apis":[{"api":"Companies House API","provider":"UK Government","auth":"API key (Basic Auth)","exists":True,"status":"AUTH_REQUIRED","data":"UK corporate filings"},{"api":"Google DoH","provider":"Google","auth":"None","exists":True,"status":"SUCCESS","data":"DNS records"},{"api":"Cloudflare DoH","provider":"Cloudflare","auth":"None","exists":True,"status":"SUCCESS","data":"DNS records"},{"api":"RDAP","provider":"IETF standard","auth":"None","exists":True,"status":"SUCCESS","data":"Domain registration"},{"api":"Wayback CDX","provider":"Internet Archive","auth":"None","exists":True,"status":"SUCCESS","data":"Historical web captures"},{"api":"GitHub API","provider":"GitHub","auth":"None (rate limited)","exists":True,"status":"SUCCESS","data":"Code repository metadata"},{"api":"iTunes Search","provider":"Apple","auth":"None","exists":True,"status":"SUCCESS","data":"App Store metadata"},{"api":"iTunes Lookup","provider":"Apple","auth":"None","exists":True,"status":"SUCCESS","data":"App details"},{"api":"Etherscan API","provider":"Etherscan","auth":"API key (optional)","exists":True,"status":"SUCCESS","data":"Ethereum blockchain"},{"api":"crt.sh","provider":"Sectigo","auth":"None","exists":True,"status":"UNAVAILABLE","data":"Certificate transparency"},{"api":"OpenSanctions","provider":"OpenSanctions","auth":"API key","exists":True,"status":"AUTH_REQUIRED","data":"Sanctions/watchlists"},{"api":"VirusTotal","provider":"VirusTotal","auth":"API key","exists":True,"status":"AUTH_REQUIRED","data":"Threat intelligence"},{"api":"FCA Register","provider":"FCA","auth":"Unknown","exists":True,"status":"403_FORBIDDEN","data":"Financial regulatory"},{"api":"Action Fraud","provider":"City of London Police","auth":"Law enforcement","exists":False,"status":"NO_PUBLIC_API","data":"Fraud reports"},{"api":"UK Gazette API","provider":"TSO","auth":"Unknown","exists":False,"status":"404_NOT_FOUND","data":"Official notices"}],"total_apis":15,"apis_successful":8,"auth_required":5,"unavailable":2,"no_api_found":2})

# 7
save("api-access-matrix.json", {"access_levels":[{"level":"PUBLIC","apis":["Google DoH","Cloudflare DoH","RDAP","Wayback CDX","GitHub API","iTunes Search","iTunes Lookup","BAILII"],"count":8},{"level":"PUBLIC_API_AUTH_REQUIRED","apis":["Companies House API","OpenSanctions","VirusTotal","Etherscan (optional)"],"count":4},{"level":"RESTRICTED","apis":["FCA Register","Open Ownership Register","Action Fraud"],"count":3},{"level":"NO_API_FOUND","apis":["UK Gazette","UK Insolvency Service"],"count":2},{"level":"UNAVAILABLE","apis":["crt.sh"],"count":1}],"total":18})

# 8
save("court-sources.json", {"sources_checked":[{"source":"BAILII (British and Irish Legal Information Institute)","url":"bailii.org","query":"smartstar+technology","result":"NO_CASES_FOUND","access":"PUBLIC"},{"source":"UK Judiciary (judiciary.uk)","url":"judiciary.uk","query":"SmartStar Technology","result":"NO_RESULTS_FOUND","access":"PUBLIC"},{"source":"UK Tribunal Decisions","url":"judiciary.uk/judgments","query":"SmartStar Technology","result":"NO_JUDGMENTS_FOUND","access":"PUBLIC"},{"source":"UK Courts and Tribunals Online","url":"courttribunalfinder.service.gov.uk","result":"NOT_CHECKED — no search API available","access":"PUBLIC (web only)"},{"source":"HMCTS (Her Majesty's Courts and Tribunals Service)","url":"gov.uk/government/organisations/hm-courts-and-tribunals-service","result":"NOT_CHECKED — no public case search API","access":"RESTRICTED"},{"source":"Companies Court (Insolvency)","url":"gov.uk","result":"NOT_CHECKED — no public API for case-by-case search","access":"RESTRICTED"}],"court_records_found":0,"note":"No court records, judgments, or tribunal decisions found for SmartStar Technology Ltd (14511663) or Rojs Gordons in any UK/Irish legal database queried. The company was dissolved via compulsory strike-off (administrative process, not court-ordered insolvency). No litigation found."})

# 9
save("government-sources.json", {"sources_checked":[{"source":"Companies House UK","url":"find-and-update.company-information.service.gov.uk","result":"SUCCESS — company data retrieved","access":"PUBLIC (web)"},{"source":"FCA Register","url":"register.fca.org.uk","result":"403_FORBIDDEN","access":"RESTRICTED"},{"source":"Open Ownership Register","url":"register.openownership.org","result":"403_FORBIDDEN","access":"RESTRICTED"},{"source":"UK Insolvency Service","url":"insolvencydirect.bis.gov.uk","result":"404_NOT_FOUND (URL changed)","access":"UNKNOWN"},{"source":"UK Gazette","url":"thegazette.co.uk","result":"404_NOT_FOUND (API)","access":"PUBLIC (web only)"},{"source":"HMRC (tax authority)","url":"gov.uk/government/organisations/hm-revenue-customs","result":"NOT_CHECKED — no public API for company tax data","access":"RESTRICTED"},{"source":"Crown Commercial Service (procurement)","url":"gov.uk/government/organisations/crown-commercial-service","result":"NOT_CHECKED — no public search for supplier records","access":"RESTRICTED"},{"source":"Information Commissioner's Office (ICO)","url":"ico.org.uk","result":"NOT_CHECKED — data protection register not queried","access":"PUBLIC (web search)"}],"government_sources_successful":1,"government_sources_restricted":4,"government_sources_unavailable":3})

# 10
save("corporate-graph.json", {"root":{"name":"SmartStar Technology Ltd","number":"14511663","jurisdiction":"UK"},"company":{"name":"SMARTSTAR TECHNOLOGY LTD","number":"14511663","status":"DISSOLVED","incorporated":"2022-11-29","dissolved":"2025-10-07","type":"Private limited Company","address":"27 Old Gloucester Street, London, WC1N 3AX (virtual office)","sic":["80200 - Security systems","82200 - Call centres","82990 - Business support"],"share_capital":"£10M nominal (100% unpaid, £10K called)","accounts":"8 employees, £263K current assets, £160K net assets","charges":0,"insolvency":"NO_INSOLVENCY (administrative dissolution)","previous_names":"NONE"},"connected_companies":[{"name":"VIP RENT LTD","number":"13500336","director":"Rojs Gordons","status":"Dissolved","sic":"77110 Car leasing"},{"name":"DEPILS LIMITED","number":"08774027","director":"Rojs Gordons","status":"Dissolved","sic":"80100 Private security"},{"name":"DIK ORMAN UK LTD","number":"14311904","director":"Rojs Gordons (ceased)","status":"Dissolved","sic":"41100/41201/43290 Construction"},{"name":"EUROPEAN DBS LTD","number":"12428261","director":"Rojs Gordons","status":"Dissolved","sic":"46900 Wholesale"},{"name":"GOLAN TRADE UK LTD","number":"12582734","director":"Rojs Gordons","status":"Dissolved","sic":"Unknown"},{"name":"TANSWA Sp. z o.o.","country":"Poland","director":"Rojs Gordons (President/100%)","status":"Active"},{"name":"SMART TRADE","country":"France","director":"Rojs Gordons (President, ceased)","status":"Active"},{"name":"REALM WONDERLAND s.r.o.","country":"Czech Republic","director":"Rojs Gordons (50%)","status":"Active"},{"name":"Golan Europe SL","country":"Spain","director":"Rojs Gordons","status":"Active"},{"name":"GGPWORLD OÜ","country":"Estonia","director":"Rojs Gordons (former)","status":"Terminated"}],"total_connected_companies":10,"all_uk_companies_dissolved":True})

# 11
save("people-graph.json", {"rojs_gordons":{"legal_name":"Rojs Gordons","dob":"April 1988 (2 April 1988 in EU registries)","nationality":"Latvian","residence":"UK (Erith, Greater London)","identity_confidence":"IDENTITY_CONFIRMED","identifiers":{"linkedin":"uk.linkedin.com/in/rojs-gordons-986928421","github":"github.com/Protremix","github_email":"info@protremix.com","whatsapp":"+44 7451 261353"},"uk_companies":6,"international_companies":5,"professional_role":"Software/blockchain developer (Protremix CEO, Verdis Chain Founder)","pattern":"Serial company formation across 5+ countries. All UK companies dissolved. Active in software/blockchain."},"rex_huang":{"legal_name":"Rex Huang (Yi-Hsuan Huang)","nationality":"Taiwanese-Kiwi","residence":"Christchurch, New Zealand","identity_confidence":"IDENTITY_CONFIRMED","identifiers":{"linkedin":"nz.linkedin.com/in/rex-huang-a9a87351","facebook":"facebook.com/rexhuang221","github":"github.com/RexHuang"},"nz_companies":2,"professional_role":"Construction professional + SmartJobs app developer"},"secretaries":[{"name":"Ola Saber Alkaddour","appointed":"2023-02-11","resigned":"2024-03-01","identity":"UNRESOLVED — no further public information found"},{"name":"Nidal Ahmad","appointed":"2023-05-17","resigned":"2024-03-01","identity":"UNRESOLVED — no further public information found"}],"relationship_uk_nz":"NOT_CONNECTED — different people, different countries, different industries, no shared identifiers, no shared infrastructure","relationship_uk_singapore":"NOT_CONNECTED — different people (Rojs Gordons vs Abin Han)"})

# 12
save("address-graph.json", {"addresses":[{"address":"27 Old Gloucester Street, London, WC1N 3AX","type":"Virtual office (British Monomarks)","companies_at_address":"4,296+","entities_using":["SmartStar Technology Ltd (UK)","VIP RENT LTD (initially)","+4,296 others"],"investigative_value":"LOW — virtual office, no physical operations"},{"address":"86-90 Paul Street, London, EC2A 4NE","type":"Virtual office","entities_using":["VIP RENT LTD"],"investigative_value":"LOW"},{"address":"49 Linton Avenue, Borehamwood, WD6 4RB","type":"Residential","entities_using":["DEPILS LIMITED","EUROPEAN DBS LTD"],"investigative_value":"MEDIUM — residential address"},{"address":"1 Linton Avenue, Borehamwood, WD6 4RB","type":"Residential","entities_using":["GOLAN TRADE UK LTD"],"investigative_value":"MEDIUM"},{"address":"20-22 Wenlock Road, London, N1 7GU","type":"Virtual office","entities_using":["DIK ORMAN UK LTD"],"investigative_value":"LOW"},{"address":"Leopoldauer Straße 131/2 34, 1210 Vienna, Austria","type":"Residential","entities_using":["Rojs Gordons (Austrian registry)"],"investigative_value":"MEDIUM"},{"address":"Calle Capitán Salom 2, Palma de Mallorca, Spain","type":"Commercial","entities_using":["Golan Europe SL"],"investigative_value":"MEDIUM"},{"address":"365b Papanui Road, Christchurch, NZ","type":"Commercial","entities_using":["SmartStar Technology Limited (NZ)"],"investigative_value":"MEDIUM — legitimate NZ business address"}],"total_addresses":8,"virtual_offices":3,"residential":3,"commercial":2,"note":"Address analysis reveals a pattern of virtual office usage for UK companies. The Borehamwood addresses (Linton Avenue) are residential and may be the actual residence of Rojs Gordons in the UK."})

# 13
save("domain-graph.json", {"domains_tested":12,"domains_resolved":4,"domains_nxdomain":6,"domains":[{"domain":"smartstar.co.uk","dns":"A: 76.223.54.146 + 13.248.169.48","mx":"0 . (null MX)","ns":"afternic.com (parked)","txt":"v=spf1 -all","rdap":"Registered 2022-10-16, registrar: sitekart","wayback":"10 captures (2017-2024)","ip_asn":"Amazon/Global Forwarding","status":"PARKED (Afternic)","note":"Registered 6 weeks before UK company. Was live 2017-2024, now parked for sale."},{"domain":"smartstar.uk","dns":"A: 72.60.233.61 (Hostinger)","mx":"mx1/mx2.hostinger.com","ns":"dns-parking.com","txt":"google-site-verification + SPF","status":"PARKED (Hostinger)"},{"domain":"smartjobs.co.uk","dns":"A: 3.33.224.147 (Aftermarket)","ns":"aftermarket.com","txt":"afternic-verification","status":"PARKED (Aftermarket)"},{"domain":"smartstartechnology.com","dns":"A: 49.212.180.142 (Sakura Internet, Japan)","mx":"smartstartechnology.com","ns":"ns1/ns2.dns.ne.jp","txt":"SPF for sakura.ne.jp","rdap":"Registered 2013-04-15 (Japan)","status":"ACTIVE (Japanese company, UNRELATED)"},{"domain":"smartstartechnology.co.uk","dns":"NXDOMAIN","rdap":"NOT_FOUND","status":"NOT_REGISTERED"},{"domain":"smartstar-technology.co.uk","dns":"NXDOMAIN","rdap":"NOT_FOUND","status":"NOT_REGISTERED"},{"domain":"sst-technology.co.uk","dns":"NXDOMAIN","status":"NOT_REGISTERED"},{"domain":"smartstar-tech.co.uk","dns":"NXDOMAIN","status":"NOT_REGISTERED"},{"domain":"smartstartech.co.uk","dns":"NXDOMAIN","status":"NOT_REGISTERED"},{"domain":"smartstartechnology.uk","dns":"NXDOMAIN","status":"NOT_REGISTERED"}],"uk_entity_domains":"NONE — UK SmartStar Technology Ltd had no registered domains, no web infrastructure, no DNS records","note":"smartstar.co.uk was registered 6 weeks before company but registrant is privacy-protected. Cannot confirm if Rojs Gordons registered it."})

# 14
save("infrastructure-graph.json", {"ips":[{"ip":"76.223.54.146","domain":"smartstar.co.uk","asn":"Amazon (Global Forwarding)","hosting":"Parked domain forwarding"},{"ip":"13.248.169.48","domain":"smartstar.co.uk","asn":"Amazon (Global Forwarding)","hosting":"Parked domain forwarding"},{"ip":"72.60.233.61","domain":"smartstar.uk","asn":"Hostinger","hosting":"Web hosting/parking"},{"ip":"3.33.224.147","domain":"smartjobs.co.uk","asn":"Amazon/Aftermarket","hosting":"Domain marketplace"},{"ip":"49.212.180.142","domain":"smartstartechnology.com","asn":"Sakura Internet (Japan)","hosting":"Japanese hosting"},{"ip":"35.190.29.89","domain":"smartjobs.io + smartjobs.co.nz","asn":"Google Cloud (AS396982)","hosting":"Google Cloud/Firebase (NZ entity)"},{"ip":"43.245.53.194","domain":"smartstar.co.nz","asn":"Dreamscape/Freeparking (AS38719)","hosting":"NZ domain hosting"},{"ip":"8.218.170.242","domain":"smartstar.sg","asn":"Alibaba Cloud (AS45102)","hosting":"Alibaba Cloud (SG entity)"}],"certificate_transparency":{"source":"crt.sh","status":"502_UNAVAILABLE","queries":5,"result":"NO_DATA (service unavailable)"},"subdomains":"NOT_CHECKED — no UK entity domains to enumerate","dnssec":"NOT_CHECKED — no UK entity domains","tls":"NOT_CHECKED — no UK entity domains to test TLS","note":"No infrastructure belongs to or was operated by the UK entity. All discovered infrastructure belongs to NZ entity (Google Cloud), SG entity (Alibaba Cloud), or parked domains (Amazon/Hostinger/Aftermarket)."})

# 15
save("email-intelligence.json", {"emails":[{"email":"info@protremix.com","source":"GitHub API (public profile)","domain":"protremix.com","associated_person":"Rojs Gordons","associated_entity":"Protremix","first_seen":"2026-08-07 (GitHub account creation)","public_references":["GitHub profile","Protremix website"],"classification":"INTELLIGENCE","mailbox_access":"NEVER_ATTEMPTED"},{"email":"info@smartstar.co.nz","source":"NZ Companies Office / domain registration","domain":"smartstar.co.nz","associated_person":"Rex Huang","associated_entity":"SmartStar Technology Limited (NZ)","classification":"INTELLIGENCE","mailbox_access":"NEVER_ATTEMPTED"}],"email_domains":[{"domain":"protremix.com","status":"ACTIVE (Protremix website)","owner":"Rojs Gordons / Protremix","source":"GitHub API + web"},{"domain":"smartstar.co.nz","status":"ACTIVE (NZ entity)","owner":"Rex Huang / SmartStar NZ","source":"DNS"},{"domain":"smartstar.co.uk","status":"PARKED (Afternic)","owner":"PRIVACY_PROTECTED","source":"RDAP"}],"shared_email_domains":0,"note":"No shared email domains between UK and NZ entities. UK entity had no public email. Rojs Gordons uses info@protremix.com (discovered via GitHub API, non-Google source)."})

# 16
save("phone-intelligence.json", {"phones":[{"number":"+44 7451 261353","format":"UK mobile (+44)","source":"Verdis Chain website (public)","associated_person":"Rojs Gordons","associated_entity":"Verdis Chain","country":"United Kingdom","carrier":"UNKNOWN (not lawfully available without authorization)","public_references":["verdischain.com/team"],"classification":"INTELLIGENCE","access_boundary":"NEVER_ATTEMPTED — no OTP interception, SIM abuse, or account takeover"}],"shared_phone_numbers":0,"note":"One phone number identified: +44 7451 261353 (Rojs Gordons, via Verdis Chain website). UK SmartStar entity had no public phone number. No phone intelligence APIs implemented."})

# 17
save("website-history.json", {"uk_entity_websites":"NONE — UK SmartStar Technology Ltd had no websites","smartstar_co_uk_history":{"first_capture":"2017-04-20","last_capture":"2024-07-27","total_captures":10,"captures":[{"date":"2017-04-20","status":"200","size":"531 bytes"},{"date":"2017-05-28","status":"200","size":"531 bytes"},{"date":"2018-08-09","status":"-","size":"438 bytes"},{"date":"2018-11-09","status":"-","size":"439 bytes"},{"date":"2021-12-25","status":"200","size":"675 bytes"},{"date":"2024-05-02","status":"301","size":"782 bytes","note":"Redirect — domain put up for sale"},{"date":"2024-05-24","status":"302","size":"398 bytes"},{"date":"2024-05-24","status":"301","size":"413 bytes"},{"date":"2024-07-15","status":"200","size":"541 bytes","note":"HTTPS — Afternic parking page"},{"date":"2024-07-27","status":"200","size":"537 bytes"}],"source":"Wayback Machine CDX API (non-Google)","note":"smartstar.co.uk existed before UK company (2017) but was never a business website. It was a simple landing page (500-700 bytes) until May 2024 when it was redirected to Afternic for sale."},"smartjobs_io":{"status":"Active website for NZ SmartStar entity","hosting":"Google Cloud","seller_url_confirmed_via":"Apple iTunes Lookup API"}})

# 18
save("app-intelligence.json", {"uk_entity_apps":"NONE — UK SmartStar Technology Ltd has no apps","nz_entity_apps":[{"app":"Smartjobs App","platform":"Apple + Google Play","bundle":"nz.smartstar.smartjobs.app","seller":"SmartStar Technology Ltd.","seller_url":"https://smartjobs.io","version":"4.2.8","release":"2026-02-23","price":"Free","genres":["Business","Productivity"],"downloads_google_play":530,"ratings":0,"description":"Manage jobs, sign-in/out, health & safety, time clock","source":"Apple iTunes API + Google Play (direct)"},{"app":"SmartJobs Reception","platform":"Apple","bundle":"org.reactjs.native.example.SJReceptionApp","seller":"SmartStar Technology Ltd.","release":"2026-01-06","source":"Apple iTunes Search API"},{"app":"Smartjobs Arcade","platform":"Apple","bundle":"com.smartjobs.arcade","seller":"SmartStar Technology Ltd.","release":"2026-04-15","source":"Apple iTunes Search API"}],"note":"3 apps published by SmartStar Technology Ltd (NZ entity). UK entity had no apps. Bundle ID prefix 'nz.smartstar' confirms NZ origin. All discovered via non-Google APIs."})

# 19
save("social-intelligence.json", {"platforms":[{"platform":"LinkedIn","api":"OAuth required","accounts":[{"name":"Rojs Gordons","url":"uk.linkedin.com/in/rojs-gordons-986928421","title":"Project Manager @ Protremix","source":"Google search (baseline)","api_access":"AUTH_REQUIRED"},{"name":"Rex Huang","url":"nz.linkedin.com/in/rex-huang-a9a87351","title":"Managing Director, SmartStar","source":"Google search (baseline)","api_access":"AUTH_REQUIRED"}]},{"platform":"GitHub","api":"Public API (rate limited)","accounts":[{"name":"Protremix","url":"github.com/Protremix","repos":4,"email":"info@protremix.com","bio":"Protremix Software, Blockchain, Platforms","created":"2026-08-07","source":"GitHub API (non-Google)","api_access":"SUCCESS"},{"name":"RexHuang","url":"github.com/RexHuang","repos":"NOT_QUERIED","source":"GitHub API available","api_access":"NOT_QUERIED"}]},{"platform":"Facebook","api":"Graph API (OAuth + app review)","accounts":[{"name":"Rex Huang","url":"facebook.com/rexhuang221","type":"Digital Creator, Christchurch","source":"Google search (baseline)","api_access":"AUTH_REQUIRED"}]},{"platform":"Twitter/X","api":"API v2 (paid)","accounts":"NONE FOUND","api_access":"AUTH_REQUIRED (paid API)"},{"platform":"Telegram","api":"Bot API (limited)","accounts":"NONE FOUND","api_access":"NOT_IMPLEMENTED"},{"platform":"Instagram","api":"Graph API (OAuth)","accounts":"NONE FOUND","api_access":"AUTH_REQUIRED"}],"social_api_connectors_implemented":1,"social_api_connectors_auth_required":4,"note":"GitHub was the only social platform accessible via public API. LinkedIn, Facebook, Twitter, Instagram all require OAuth. Telegram not implemented."})

print("Part 1: 19 artifacts created")
